name: build
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.12
        uses: actions/setup-go@v1
        with:
          go-version: 1.12

      - name: Check out source code
        uses: actions/checkout@v1

      # only for projects using Go modules
      - name: Download Go dependencies
        run: go mod download

      - name: Build
        run: go build .
